spring.application.name=dilib

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dilib
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=always

jwt.secret = itShouldBeLongAndHidden
